pub struct ClientDef {
    pub id: &'static str,
    pub name: &'static str,
    pub client_type: &'static str,
    pub config_path: Option<&'static str>,
    pub config_path_win: Option<&'static str>,
    pub config_key: &'static str,
    pub config_format: &'static str,
    pub detection_kind: &'static str,
    pub detection_value: Option<&'static str>,
}

pub static REGISTRY: &[ClientDef] = &[
    ClientDef {
        id: "claude-desktop",
        name: "Claude Desktop",
        client_type: "Desktop",
        config_path: Some("~/Library/Application Support/Claude/claude_desktop_config.json"),
        config_path_win: Some("%APPDATA%\\Claude\\claude_desktop_config.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Claude.app"),
    },
    ClientDef {
        id: "claude-code",
        name: "Claude Code",
        client_type: "CLI",
        config_path: Some("~/.claude.json"),
        config_path_win: Some("%USERPROFILE%\\.claude.json"),
        config_key: "projects.{HOME}.mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("claude"),
    },
    ClientDef {
        id: "claude-web",
        name: "Claude (web)",
        client_type: "Web",
        config_path: None,
        config_path_win: None,
        config_key: "",
        config_format: "json",
        detection_kind: "none",
        detection_value: None,
    },
    ClientDef {
        id: "chatgpt-desktop",
        name: "ChatGPT Desktop",
        client_type: "Desktop",
        config_path: None,
        config_path_win: None,
        config_key: "",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/ChatGPT.app"),
    },
    ClientDef {
        id: "chatgpt",
        name: "ChatGPT",
        client_type: "Web",
        config_path: None,
        config_path_win: None,
        config_key: "",
        config_format: "json",
        detection_kind: "none",
        detection_value: None,
    },
    ClientDef {
        id: "codex-app",
        name: "Codex",
        client_type: "Desktop",
        config_path: Some("~/.codex/config.toml"),
        config_path_win: Some("%USERPROFILE%\\.codex\\config.toml"),
        config_key: "mcp_servers",
        config_format: "toml",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Codex.app"),
    },
    ClientDef {
        id: "codex-cli",
        name: "Codex CLI",
        client_type: "CLI",
        config_path: Some("~/.codex/config.toml"),
        config_path_win: Some("%USERPROFILE%\\.codex\\config.toml"),
        config_key: "mcp_servers",
        config_format: "toml",
        detection_kind: "cli_binary",
        detection_value: Some("codex"),
    },
    ClientDef {
        id: "gemini-cli",
        name: "Gemini CLI",
        client_type: "CLI",
        config_path: Some("~/.gemini/settings.json"),
        config_path_win: Some("%USERPROFILE%\\.gemini\\settings.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("gemini"),
    },
    ClientDef {
        id: "antigravity",
        name: "Antigravity",
        client_type: "IDE",
        config_path: Some("~/.gemini/antigravity/mcp_config.json"),
        config_path_win: Some("%USERPROFILE%\\.gemini\\antigravity\\mcp_config.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Antigravity.app"),
    },
    ClientDef {
        id: "github-copilot",
        name: "GitHub Copilot",
        client_type: "IDE",
        config_path: Some("~/Library/Application Support/Code/User/mcp.json"),
        config_path_win: Some("%APPDATA%\\Code\\User\\mcp.json"),
        config_key: "servers",
        config_format: "json",
        detection_kind: "vscode_extension",
        detection_value: Some("github.copilot-chat"),
    },
    ClientDef {
        id: "github-copilot-cli",
        name: "GitHub Copilot CLI",
        client_type: "CLI",
        config_path: Some("~/.copilot/mcp-config.json"),
        config_path_win: Some("%USERPROFILE%\\.copilot\\mcp-config.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("copilot"),
    },
    ClientDef {
        id: "cursor",
        name: "Cursor",
        client_type: "IDE",
        config_path: Some("~/.cursor/mcp.json"),
        config_path_win: Some("%USERPROFILE%\\.cursor\\mcp.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Cursor.app"),
    },
    ClientDef {
        id: "windsurf",
        name: "Windsurf",
        client_type: "IDE",
        config_path: Some("~/.codeium/windsurf/mcp_config.json"),
        config_path_win: Some("%USERPROFILE%\\.codeium\\windsurf\\mcp_config.json"),
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Windsurf.app"),
    },
];

pub fn find_client(id: &str) -> Option<&'static ClientDef> {
    REGISTRY.iter().find(|c| c.id == id)
}

pub fn platform_config_path(c: &ClientDef) -> Option<&'static str> {
    #[cfg(windows)]
    return c.config_path_win;
    #[cfg(not(windows))]
    return c.config_path;
}
