pub struct ClientDef {
    pub id: &'static str,
    pub name: &'static str,
    pub client_type: &'static str,
    pub config_path: Option<&'static str>,
    pub config_path_win: Option<&'static str>,
    pub config_path_linux: Option<&'static str>,
    pub config_key: &'static str,
    pub config_format: &'static str,
    pub detection_kind: &'static str,
    pub detection_value: Option<&'static str>,
    /// Windows-specific detection path for app_bundle clients (expands %LOCALAPPDATA% etc.)
    pub detection_value_win: Option<&'static str>,
    /// Linux-specific detection path for app_bundle clients
    pub detection_value_linux: Option<&'static str>,
    /// Skills directory path for clients that support skills (None = not supported)
    pub skills_path: Option<&'static str>,
    /// Agent ID for `npx skills add --agent <id>` (None = use file-copy fallback)
    pub npx_agent_id: Option<&'static str>,
}

pub static REGISTRY: &[ClientDef] = &[
    ClientDef {
        id: "claude-desktop",
        name: "Claude Desktop",
        client_type: "Desktop",
        config_path: Some("~/Library/Application Support/Claude/claude_desktop_config.json"),
        config_path_win: Some("%APPDATA%\\Claude\\claude_desktop_config.json"),
        config_path_linux: None, // Not supported on Linux
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Claude.app"),
        detection_value_win: Some("%LOCALAPPDATA%\\Microsoft\\WindowsApps\\Claude.exe|%LOCALAPPDATA%\\AnthropicClaude\\Update.exe"),
        detection_value_linux: None,
        skills_path: Some("~/Library/Application Support/Claude/skills"),
        npx_agent_id: None,
    },
    ClientDef {
        id: "claude-code",
        name: "Claude Code",
        client_type: "CLI",
        config_path: Some("~/.claude.json"),
        config_path_win: Some("%USERPROFILE%\\.claude.json"),
        config_path_linux: None, // Same as config_path
        config_key: "projects.{HOME}.mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("claude"),
        detection_value_win: None, // binary name same everywhere; probe handles .cmd
        detection_value_linux: None,
        skills_path: Some("~/.claude/skills"),
        npx_agent_id: Some("claude-code"),
    },
    ClientDef {
        id: "claude-web",
        name: "Claude (web)",
        client_type: "Web",
        config_path: None,
        config_path_win: None,
        config_path_linux: None,
        config_key: "",
        config_format: "json",
        detection_kind: "none",
        detection_value: None,
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: None,
        npx_agent_id: None,
    },
    ClientDef {
        id: "chatgpt-desktop",
        name: "ChatGPT Desktop",
        client_type: "Desktop",
        config_path: None,
        config_path_win: None,
        config_path_linux: None,
        config_key: "",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/ChatGPT.app"),
        detection_value_win: Some("%LOCALAPPDATA%\\Microsoft\\WindowsApps\\ChatGPT.exe"),
        detection_value_linux: None,
        skills_path: None,
        npx_agent_id: None,
    },
    ClientDef {
        id: "chatgpt",
        name: "ChatGPT",
        client_type: "Web",
        config_path: None,
        config_path_win: None,
        config_path_linux: None,
        config_key: "",
        config_format: "json",
        detection_kind: "none",
        detection_value: None,
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: None,
        npx_agent_id: None,
    },
    ClientDef {
        id: "codex-app",
        name: "Codex",
        client_type: "Desktop",
        config_path: Some("~/.codex/config.toml"),
        config_path_win: Some("%USERPROFILE%\\.codex\\config.toml"),
        config_path_linux: None, // Same as config_path
        config_key: "mcp_servers",
        config_format: "toml",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Codex.app"),
        detection_value_win: Some("%LOCALAPPDATA%\\Programs\\Codex\\Codex.exe"),
        detection_value_linux: None,
        skills_path: None,
        npx_agent_id: None,
    },
    ClientDef {
        id: "codex-cli",
        name: "Codex CLI",
        client_type: "CLI",
        config_path: Some("~/.codex/config.toml"),
        config_path_win: Some("%USERPROFILE%\\.codex\\config.toml"),
        config_path_linux: None,
        config_key: "mcp_servers",
        config_format: "toml",
        detection_kind: "cli_binary",
        detection_value: Some("codex"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: Some("~/.codex/skills"),
        npx_agent_id: Some("codex"),
    },
    ClientDef {
        id: "opencode",
        name: "OpenCode",
        client_type: "IDE",
        config_path: Some("~/.config/opencode/opencode.json"),
        config_path_win: Some("%APPDATA%\\opencode\\opencode.json"),
        config_path_linux: None, // Same as config_path
        config_key: "mcp",
        config_format: "json-opencode",
        detection_kind: "cli_binary",
        detection_value: Some("opencode"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: Some("~/.agents/skills"),
        npx_agent_id: Some("opencode"),
    },
    ClientDef {
        id: "gemini-cli",
        name: "Gemini CLI",
        client_type: "CLI",
        config_path: Some("~/.gemini/settings.json"),
        config_path_win: Some("%USERPROFILE%\\.gemini\\settings.json"),
        config_path_linux: None,
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("gemini"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: Some("~/.gemini/skills"),
        npx_agent_id: Some("gemini-cli"),
    },
    ClientDef {
        id: "mcpporter",
        name: "MCPorter (OpenClaw)",
        client_type: "CLI",
        config_path: Some("~/.mcporter/mcporter.json"),
        config_path_win: Some("%USERPROFILE%\\.mcporter\\mcporter.json"),
        config_path_linux: None, // Same as config_path
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("mcporter"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: None,
        npx_agent_id: None,
    },
    ClientDef {
        id: "antigravity",
        name: "Antigravity",
        client_type: "IDE",
        config_path: Some("~/.gemini/antigravity/mcp_config.json"),
        config_path_win: Some("%USERPROFILE%\\.gemini\\antigravity\\mcp_config.json"),
        config_path_linux: None,
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Antigravity.app"),
        detection_value_win: None,
        detection_value_linux: Some("/usr/bin/antigravity"),
        skills_path: Some("~/.antigravity/skills"),
        npx_agent_id: None,
    },
    ClientDef {
        id: "github-copilot",
        name: "GitHub Copilot",
        client_type: "IDE",
        config_path: Some("~/Library/Application Support/Code/User/mcp.json"),
        config_path_win: Some("%APPDATA%\\Code\\User\\mcp.json"),
        config_path_linux: Some("~/.config/Code/User/mcp.json"),
        config_key: "servers",
        config_format: "json",
        detection_kind: "vscode_extension",
        detection_value: Some("github.copilot-chat"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: Some("~/.copilot/skills"),
        npx_agent_id: None,
    },
    ClientDef {
        id: "github-copilot-cli",
        name: "GitHub Copilot CLI",
        client_type: "CLI",
        config_path: Some("~/.copilot/mcp-config.json"),
        config_path_win: Some("%USERPROFILE%\\.copilot\\mcp-config.json"),
        config_path_linux: None,
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "cli_binary",
        detection_value: Some("copilot"),
        detection_value_win: None,
        detection_value_linux: None,
        skills_path: Some("~/.copilot/skills"),
        npx_agent_id: None,
    },
    ClientDef {
        id: "cursor",
        name: "Cursor",
        client_type: "IDE",
        config_path: Some("~/.cursor/mcp.json"),
        config_path_win: Some("%USERPROFILE%\\.cursor\\mcp.json"),
        config_path_linux: None, // Same as config_path
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Cursor.app"),
        detection_value_win: Some("%LOCALAPPDATA%\\Programs\\cursor\\Cursor.exe"),
        detection_value_linux: Some("/usr/bin/cursor"),
        skills_path: Some("~/.cursor/skills"),
        npx_agent_id: Some("cursor"),
    },
    ClientDef {
        id: "windsurf",
        name: "Windsurf",
        client_type: "IDE",
        config_path: Some("~/.codeium/windsurf/mcp_config.json"),
        config_path_win: Some("%USERPROFILE%\\.codeium\\windsurf\\mcp_config.json"),
        config_path_linux: None,
        config_key: "mcpServers",
        config_format: "json",
        detection_kind: "app_bundle",
        detection_value: Some("/Applications/Windsurf.app"),
        detection_value_win: Some("%LOCALAPPDATA%\\Programs\\Windsurf\\Windsurf.exe"),
        detection_value_linux: Some("/usr/bin/windsurf"),
        skills_path: Some("~/.codeium/windsurf/skills"),
        npx_agent_id: Some("windsurf"),
    },
];

pub fn find_client(id: &str) -> Option<&'static ClientDef> {
    REGISTRY.iter().find(|c| c.id == id)
}

pub fn platform_config_path(c: &ClientDef) -> Option<&'static str> {
    #[cfg(windows)]
    return c.config_path_win;
    #[cfg(target_os = "linux")]
    return c.config_path_linux.or(c.config_path);
    #[cfg(not(any(windows, target_os = "linux")))]
    return c.config_path;
}

pub fn platform_skills_path(c: &ClientDef) -> Option<&'static str> {
    c.skills_path
}
